### ISSUE TITLE
Stopping depending on the Windows Cookbook?

### ISSUE THREAD

**Issue by damacus** [sous-chefs/seven_zip#20]
If possible I'd like to remove the dependency on the Windows cookbook. 

If we dep on it right now we see [this](https://travis-ci.org/sous-chefs/postgresql/jobs/392590995) from recent Chef version. Which made me think how much of the Windows cookbook do we actually need? How much is just convenience, and we can remove a dependency from the chain.

**Comment by robnasby** [comment]
I' just submitted a pull request for this... #24
